import "./globals.css";
import Providers from "./Providers";
import { Toaster } from "sonner";

export const metadata = {
  title: "jungleZone.uk",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Providers>{children}</Providers>
        <Toaster position="top-right" richColors closeButton />
      </body>
    </html>
  );
}
